version: '3.9'

services:
  stremio:
    build: .
    ports:
      - '11470:11470'
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./data/:/root/.stremio-server
      - ./files/patches.js:/srv/stremio/web/patches.js:ro
      - ./files/patches.js:/srv/stremio/shell/patches.js:ro
    env_file:
      - .env
