version: '3.9'

services:
  app:
    build:
      context: .
      args:
        CHECKOUT: ${CHECKOUT:-master}
    restart: unless-stopped
    expose: [ '4567' ]
    networks: [ 'default' ]
    depends_on: [ 'db' ]
    volumes: [ './data/nodebb:/data' ]

  db:
    image: postgres:latest
    restart: unless-stopped
    expose: [ '5432' ]
    networks: [ 'default' ]
    env_file: [ '.env' ]
    volumes: [ './data/postgres:/var/lib/postgresql/data' ]
