version: '3.8'

services:
  go:
    build: .
    container_name: brave-sync
    restart: always
    ports: [ '8295:8295' ]
    networks: [ 'default' ]
    volumes:
      - ./data/src:${WORK_DIR:-/srv/go-sync}:ro
    depends_on:
      - dynamodb
      - redis
    environment:
      WORK_DIR: ${WORK_DIR:-/srv/go-sync}
      PPROF_ENABLED: ${PPROF_ENABLED:-true}
      SENTRY_DSN: ${SENTRY_DSN:-}
      ENV: ${ENV:-local}
      DEBUG: ${DEBUG:-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-#}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-#}
      AWS_REGION: ${AWS_REGION:-us-west-2}
      AWS_ENDPOINT: ${AWS_ENDPOINT:-http://dynamodb:8000}
      TABLE_NAME: ${TABLE_NAME:-client-entity-dev}
      REDIS_URL: ${REDIS_URL:-redis:6379}

  dynamodb:
    image: amazon/dynamodb-local:latest
    restart: always
    networks: [ 'default' ]
    volumes:
      - ./data/data/dynamodb:/home/dynamodblocal/data
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    working_dir: /home/dynamodblocal

  redis:
    image: redis:alpine
    restart: always
    networks: [ 'default' ]
    volumes:
      - ./data/data/redis-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  default:
    name: brave-sync
    driver: bridge
