version: '3.9'

services:
  client:
    image: nginxinc/nginx-unprivileged:mainline-alpine
    restart: unless-stopped
    expose: [ '8080' ]
    ports: [ '${WEB_PORT}:8080' ]
    depends_on: [ 'server' ]
    environment:
      WEB_HOSTNAME: ${WEB_HOSTNAME}
      GAME_ADDRESS: ${GAME_ADDRESS}
      GAME_LOGIN_PORT: ${GAME_LOGIN_PORT}
      GAME_BLIZZARD_PORT: ${GAME_BLIZZARD_PORT}
    volumes:
      - ./.data/dockerize:/usr/local/bin/dockerize:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
      - ./templates/yukon.conf.template:/etc/nginx/conf.d/yukon.conf.template:ro
    command: dockerize -template /etc/nginx/conf.d/yukon.conf.template:/etc/nginx/conf.d/yukon.conf nginx "-g daemon off;"

  server:
    image: node:alpine
    restart: unless-stopped
    user: node
    expose: [ '${GAME_LOGIN_PORT}', '${GAME_BLIZZARD_PORT}' ]
    networks: [ 'default', 'db' ]
    depends_on: [ 'mariadb' ]
    env_file: [ '.env' ]
    working_dir: /srv/server
    volumes:
      - ./.data/dockerize:/usr/local/bin/dockerize:ro
      - ./.data/ssl:/etc/ssl/yukon:ro
      - ./server:/srv/server
      - ./templates/config.json.template:/srv/templates/config.json.template:ro
    command: dockerize -template /srv/templates/config.json.template:/srv/server/config/config.json -wait tcp://${MARIADB_HOST}:${MARIADB_PORT} -timeout 20s npx pm2-runtime start ecosystem.config.js

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    user: mysql
    expose: [ '3306' ]
    networks: [ 'db' ]
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./.data/mariadb:/var/lib/mysql
      - ./server/yukon.sql:/docker-entrypoint-initdb.d/yukon.sql:ro

  setup:
    profiles: [ 'dev' ]
    image: node:alpine
    working_dir: /srv/yukon
    env_file: [ '.env' ]
    volumes:
      - ./:/srv/yukon
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache git runuser
        runuser -u node -- sh ./setup.sh

  phpmyadmin:
    profiles: [ 'tools' ]
    image: phpmyadmin
    restart: unless-stopped
    expose: [ '80' ]
    networks: [ 'db' ]
    environment:
      - PMA_HOST=mariadb

networks:
  db:
