version: '3.9'

services:
  client:
    image: yukon/client
    build: ./client
    restart: unless-stopped
    ports: [ '${WEB_PORT}:80' ]
    networks: [ 'default' ]
    depends_on: [ 'server' ]
    env_file: [ '.env' ]
    volumes:
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
      - ./templates/yukon.conf.template:/etc/nginx/conf.d/yukon.conf.template
    command: [
        'dockerize',
        '-template', '/etc/nginx/conf.d/yukon.conf.template:/etc/nginx/conf.d/yukon.conf',
        'nginx', '-g', 'daemon off;'
      ]

  server:
    image: yukon/server
    build: ./server
    restart: unless-stopped
    # ports: [ '${GAME_LOGIN_PORT}:${GAME_LOGIN_PORT}', '${GAME_BLIZZARD_PORT}:${GAME_BLIZZARD_PORT}' ]
    networks: [ 'default', 'db' ]
    depends_on: [ 'mariadb' ]
    env_file: [ '.env' ]
    volumes:
      - ./server/ssl:/etc/ssl/yukon:ro
      - ./server/src:/srv/server/
      - ./templates/config.json.template:/srv/templates/config.json.template
    command: [
        'dockerize',
        '-template', '/srv/templates/config.json.template:/srv/server/config/config.json',
        '-wait', 'tcp://${MARIADB_HOST}:${MARIADB_PORT}', '-timeout', '20s',
        'npx', 'pm2-runtime', 'start', 'ecosystem.config.js'
      ]

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    # ports: [ '${MARIADB_PORT}:3306' ]
    networks: [ 'db' ]
    env_file: [ '.env' ]
    volumes:
      - ./.data:/var/lib/mysql
      - ./server/src/yukon.sql:/docker-entrypoint-initdb.d/yukon.sql:ro

  node:
    image: node:alpine
    profiles: [ 'dev' ]
    working_dir: /srv/yukon
    command: [ 'sh' ]
    volumes:
      - ./client/src:/srv/yukon/client
      - ./server/src:/srv/yukon/server

  builder:
    image: node:alpine
    profiles: [ 'dev' ]
    working_dir: /srv/yukon
    env_file: [ '.env' ]
    volumes:
      - ./client/src:/srv/yukon/client
      - ./server/src:/srv/yukon/server
      - ./www:/srv/yukon/www
    environment:
      CLIENT_BRANCH: main
      SERVER_BRANCH: master
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache git
        git clone https://github.com/wizguin/yukon.git client
        git clone https://github.com/wizguin/yukon-server.git server
        cd client && npm ci && npm run build
        cd ../server && npm ci && npm run build
        cd .. && cp -r client/assets www && cp -r client/dist/* www
        mkdir -p www/assets/scripts/lib/ruffle
        wget -qO res.json https://api.github.com/repos/ruffle-rs/ruffle/releases
        node -p "require('./res.json').flatMap(x => x.assets).find(y => y.browser_download_url.includes('selfhosted')).browser_download_url;" | xargs -n1 wget -qO ruffle.zip
        unzip -d www/assets/scripts/lib/ruffle ruffle.zip

networks:
  db:
    external: false
