version: '3.9'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    hostname: ${SYNAPSE_SERVER_NAME}
    expose: [ '8008', '8448' ]
    volumes: [ './.data/synapse:/data' ]
    networks: [ 'backend' ]
    depends_on: [ 'db' ]
    environment:
      # all env variables: https://github.com/matrix-org/synapse/blob/develop/docker/conf/homeserver.yaml
      - SYNAPSE_SERVER_NAME
      - SYNAPSE_REPORT_STATS
      - SYNAPSE_NO_TLS
      - SYNAPSE_REGISTRATION_SHARED_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  db:
    image: postgres:alpine
    restart: unless-stopped
    expose: [ '5432' ]
    volumes: [ './.data/db:/var/lib/postgresql/data' ]
    networks: [ 'backend' ]
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    expose: [ '80' ]
    volumes: [ './element-config.json:/app/config.json:ro' ]
    networks: [ 'web' ]
    profiles: [ 'element' ]

  synadmin:
    image: awesometechnologies/synapse-admin:latest
    restart: unless-stopped
    expose: [ '80' ]
    networks: [ 'web' ]
    profiles: [ 'tools' ]

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    expose: [ '80', '443' ]
    volumes: [ './.data/pgadmin:/var/lib/pgadmin' ]
    networks: [ 'backend' ]
    profiles: [ 'tools' ]
    depends_on: [ 'db' ]
    environment:
      # all env variables: https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD

networks:
  web:
  backend:
