version: '3.9'

services:
  fosscord:
    depends_on: [ 'mariadb' ]
    command: sh -c 'wait-for mariadb:3306 -- npm --prefix src run start'

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    expose: [ '3306' ]
    env_file: [ '../.env' ]
    volumes: [ '../.data/mariadb:/var/lib/mysql' ]
