version: '3.9'

services:
  fosscord:
    depends_on: [ 'postgres' ]
    command: sh -c 'wait-for postgres:5432 -- npm --prefix src run start'

  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose: [ '5432' ]
    env_file: [ '../.env' ]
    volumes: [ '../.data/postgres:/var/lib/postgresql/data' ]
