version: '3.9'

services:
  stremio:
    image: n0bodysec/stremio
    ports:
      - '11470:11470'
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./data/:/root/.stremio-server
    environment:
      APPLY_PATCHES: ${APPLY_PATCHES:-1}
      FIX_UNSUPPORTED_MEDIA: ${FIX_UNSUPPORTED_MEDIA:-1}
      NO_CORS: ${NO_CORS:-1}
