version: '3.9'

services:
  stremio:
    image: stremio
    build: .
    ports:
      - '11470:11470'
      - '8080:8080'
    volumes:
      - ./data/:/root/.stremio-server
    environment:
      RUN_PATCHES: 1
      NO_CORS: 1
