version: '3.9'

services:
  stremio:
    build: .
    ports:
      - '11470:11470'
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./data/:/root/.stremio-server
    env_file:
      - .env
