version: '3.9'

services:
  fosscord:
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    env_file: [ '.env' ]
    volumes: [ './data/mariadb/:/var/lib/mysql' ]
