version: '3.9'

services:
  fosscord:
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-secr3tpassw0rd}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-fosscord}
      MARIADB_USER: ${MARIADB_USER:-fosscord}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    volumes: [ './data/mariadb/:/var/lib/mysql' ]
