version: '3.8'

services:
  fosscord:
    container_name: fosscord
    image: fosscord
    restart: on-failure:5
    # depends_on: mariadb
    build:
      context: .
      args:
        DEV_BUILD: ${DEV_MODE:-0}
    ports:
      - '3001-3005:3001-3005'
    volumes:
      - ./dev/:${WORK_DIR:-/srv/fosscord-server}-dev/
      - data:${WORK_DIR:-/srv/fosscord-server}/
    environment:
      WORK_DIR: ${WORK_DIR:-/srv/fosscord-server}
      DEV_MODE: ${DEV_MODE:-0}
      THREADS: ${THREADS:-1}
      DATABASE: ${DATABASE:-../../data/database.db}
      STORAGE_LOCATION: ${STORAGE_LOCATION:-../../data/files/}
      HTTP_PORT: 3001
      WS_PORT: 3002
      CDN_PORT: 3003
      RTC_PORT: 3004
      ADMIN_PORT: 3005

  # mariadb:
  #   image: mariadb:latest
  #   restart: on-failure:5
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secr3tpassw0rd}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE:-fosscord}
  #     MYSQL_USER: ${MYSQL_USER:-fosscord}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password1}
  #   networks:
  #     - default
  #   volumes:
  #     - mariadb:/var/lib/mysql

volumes:
  data:
  # mariadb:

networks:
  default:
    name: fosscord
    driver: bridge
