version: '3.9'

services:
  fosscord:
    image: fosscord
    restart: unless-stopped
    build:
      context: .
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    ports: [ '3001-3004:3001-3004' ]
    expose: [ '3001', '3002', '3003', '3004' ]
    env_file: [ '.env' ]
    volumes:
      - './data/fosscord/:/srv/fosscord-server/'
      - './data/scripts:/srv/scripts/:ro'
