version: '3.9'

services:
  fosscord:
    image: fosscord
    restart: unless-stopped
    build: .
    ports: [ '3001-3003:3001-3003' ]
    volumes:
      - './data/fosscord/:/srv/fosscord-server/'
      - './data/scripts:/srv/scripts/:ro'
    environment:
      THREADS: ${THREADS:-1}
      DATABASE: ${DATABASE:-../data/database.db}
      STORAGE_LOCATION: ${STORAGE_LOCATION:-../data/files/}
      HTTP_PORT: 3001
      WS_PORT: 3002
      CDN_PORT: 3003
